# Generated by Django 6.0.5 on 2026-05-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContrattoTelefonico',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dataAttivazione', models.DateField()),
                ('tipo', models.CharField(choices=[('consumo', 'A consumo'), ('ricarica', 'Ricaricabile')], max_length=20)),
                ('minutiResidui', models.IntegerField(default=0)),
                ('creditoResiduo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'ContrattoTelefonico',
            },
        ),
        migrations.CreateModel(
            name='SIMDisattiva',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipoSIM', models.CharField(choices=[('Nano', 'Nano SIM'), ('Micro', 'Micro SIM'), ('Standard', 'Standard SIM'), ('eSIM', 'Virtuale eSIM')], max_length=20)),
                ('eraAssociataA', models.CharField(max_length=20)),
                ('dataAttivazione', models.DateField()),
                ('dataDisattivazione', models.DateField()),
            ],
            options={
                'db_table': 'SIMDisattiva',
            },
        ),
        migrations.CreateModel(
            name='SIMNonAttiva',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipoSIM', models.CharField(choices=[('Nano', 'Nano SIM'), ('Micro', 'Micro SIM'), ('Standard', 'Standard SIM'), ('eSIM', 'Virtuale eSIM')], max_length=20)),
            ],
            options={
                'db_table': 'SIMNonAttiva',
            },
        ),
        migrations.CreateModel(
            name='SIMAttiva',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipoSIM', models.CharField(choices=[('Nano', 'Nano SIM'), ('Micro', 'Micro SIM'), ('Standard', 'Standard SIM'), ('eSIM', 'Virtuale eSIM')], max_length=20)),
                ('dataAttivazione', models.DateField()),
                ('associataA', models.OneToOneField(db_column='associataA', on_delete=django.db.models.deletion.CASCADE, to='gestionale.contrattotelefonico')),
            ],
            options={
                'db_table': 'SIMAttiva',
            },
        ),
        migrations.CreateModel(
            name='Telefonata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('durata', models.IntegerField(help_text='Durata in secondi')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effettuataDa', models.ForeignKey(db_column='effettuataDa', on_delete=django.db.models.deletion.CASCADE, to='gestionale.contrattotelefonico')),
            ],
            options={
                'db_table': 'Telefonata',
            },
        ),
    ]
